### ISSUE TITLE
Seg Fault in GetLastRecord()

### ISSUE THREAD

**Issue by kishan-v** [ADimoska/SOMASExtended#127]
Hey guys, I ran into this runtime error in `AuditRecord.GetLastRecord`

It seems to be an error with Team 1's agent when running on the Team 2 AoA

Cause: when `a.auditMap[agentId]` is empty

```console
Processing pair 1-2 (candidate 1: 1, candidate 2: 2), score: 1
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/ADimoska/SOMASExtended/common.(*AuditRecord).GetLastRecord(...)
	/home/runner/work/SOMASExtended/SOMASExtended/common/Audit.go:84
github.com/ADimoska/SOMASExtended/common.(*Team2AoA).SetWithdrawalAuditResult(0xc00007f170, {0xcc, 0x62, 0xbc, 0x7c, 0xeb, 0xf3, 0x4c, 0xcb, 0xa1, ...}, ...)
	/home/runner/work/SOMASExtended/SOMASExtended/common/Team2AoA.go:121 +0x18f
github.com/ADimoska/SOMASExtended/server.(*EnvironmentServer).RunTurnDefault(0xc00013c000, 0xc00007a190)
	/home/runner/work/SOMASExtended/SOMASExtended/server/EnvironmentServer.go:108 +0x729
github.com/ADimoska/SOMASExtended/server.(*EnvironmentServer).RunTurn(0xc00013c000, 0x0?, 0x0)
	/home/runner/work/SOMASExtended/SOMASExtended/server/EnvironmentServer.go:345 +0x331
github.com/MattSScott/basePlatformSOMAS/v2/pkg/server.(*BaseServer[...]).Start(0x68ae80)
	/home/runner/go/pkg/mod/github.com/!matt!s!scott/base!platform!s!o!m!a!s/v2@v2.1.0/pkg/server/baseServer.go:111 +0x99
github.com/ADimoska/SOMASExtended/server.(*EnvironmentServer).Start(...)
	/home/runner/work/SOMASExtended/SOMASExtended/server/EnvironmentServer.go:592
main.main()
	/home/runner/work/SOMASExtended/SOMASExtended/main.go:80 +0x839```

**Comment by kishan-v** [comment]
@arnavxkohli have you seen this before?

**Comment by johanjino** [comment]
Same I get this too

**Comment by arnavxkohli** [comment]
What branch was this on?

**Comment by kishan-v** [comment]
@arnavxkohli thank you for the swift reply! trying it now
